workflows:
    android-app:
        name: Android App
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - build/outputs/**/**/*.apk
        publishing:
          email:
            recipients:
              - manimv1268@gmail.com    