workflows:
    android-app:
        name: Android App
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - app/build/outputs/apk/debug/*.apk
        publishing:
          email:
            recipients:
              - manimv1268@gmail.com    